use_frameworks!

platform :ios, '8.0'

target 'testSmart_Example' do
  pod 'testSmart', :path => '../'

  target 'testSmart_Tests' do
    inherit! :search_paths

    pod 'Kiwi'
    pod 'FBSnapshotTestCase'
  end
end
